/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.engcia;

import org.engcia.model.Evidence;
import org.engcia.model.Hypothesis;
import org.engcia.model.Conclusion;
import org.engcia.model.Fact;

import function org.engcia.view.UI.answer;

query "Conclusions"
	$conclusion : Conclusion()
end

rule "r1"
	when
		eval(answer(Evidence.BLOOD_EAR, "yes" ))
	then
		Hypothesis h = new Hypothesis("triage", "upper type");
		insert(h);
end

rule "r2"
	when
		eval(answer(Evidence.BLOOD_EAR, "no" ))
	then
		Hypothesis h = new Hypothesis("haemorrhage", "lower type");
		insert(h);
end

rule "r3"
	when
		Hypothesis( description == "triage", value == "upper type")
		eval(answer(Evidence.BLOOD_EAR, "yes"))
	then
		Conclusion c = new Conclusion(Conclusion.RED);
		insert(c);
end

rule "unknown"
	when
		not Conclusion()
	then
		Conclusion c = new Conclusion(Conclusion.UNKNOWN);
		insert(c);
end

query "evidence"(String ev, String v)
	e : Evidence( evidence == ev, value == v )
end

